spring:
  profiles.include:
    datasource-mysql,
    jwt,
    liquibase-mysql,
    cache,
    cors
  config:
    import:
      resource:common/
  jpa:
    open-in-view: false
  banner.location: classpath:/common/banner


server:
  port: 9090
