spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/postgres/changelog-master.xml
    database-change-log-lock-table: LIQUIBASECHANGELOGLOCK # Name of table to use for tracking concurrent Liquibase usage.
    database-change-log-table: LIQUIBASECHANGELOG # Name of table to use for tracking change history.
    drop-first: false
