export const PERMISSION_CODE = {
    USER_EDIT: 'USER_EDIT',
    ROLE_EDIT: 'ROLE_EDIT',
    PRODUCT_EDIT: 'PRD_EDIT',
    PACKAGE_EDIT: 'PKG_EDIT',
    CLUSTER_EDIT: 'CLUS_EDIT',
    NODE_EDIT: 'NODE_EDIT',
    PROCESS_EDIT: 'PRCS_EDIT'
};
