version: '2.0'
services:
  local-mongo:
    platform: linux/x86_64
    container_name: local-mongo
    image: mongo:4.4.5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root@2021
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./mongo:/data/db
      - ./mongoconfig:/data/configdb
  local-mysql:
    platform: linux/x86_64
    container_name: local-mysql
    image: mysql:8.0
    ports:
      - 5432:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Root@2018
      - MYSQL_DATABASE=root
    command: mysqld --sql_mode=""
    volumes:
      - ./mysql:/var/lib/mysql
  local-neo4j:
    image: neo4j/neo4j-arm64-experimental:4.2.5-arm64
    container_name: local-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j@2021
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./neo4j:/data
      - ./import:/import
