# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup jdk
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15

      - name: Grand permission mvnw
        run: chmod +x mvnw

      - name: Cache node module
        uses: actions/cache@v2.1.3
        with:
          path: office-space-frontend/src/main/web/office-space-web/node_modules
          key: ${{ runner.os }}-npmbuild-${{ hashFiles('office-space-frontend/src/main/web/office-space-web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npmbuild-

      - name: Cache maven dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-mavenbuild-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-mavenbuild-

      - name: Clean install
        run: ./mvnw clean install -Dmaven.test.skip=true
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          path: office-space-backend/target/^OfficeSpace-.{5,}.jar$
      
