name: Test Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testInte:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.number }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup jdk
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15

      - name: Chmod mvnw
        run: chmod +x mvnw

      - name: Cache maven dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maventestInte-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maventestInte-

      - name: Clean test integration
        run: ./mvnw clean -Dgroups=integration test -Pno-front-end
